Algoritmo "ex20"

Var

   a, b, soma, sub, mul, divi: real

Inicio

   escreva("Digite um valor para a: ")
   leia(a)
   escreva("Digite um valor para b: ")
   leia(b)
   
   soma <- a + b
   sub <- a - b
   mul <- a * b
   divi <- a / b

   escrevaL("x = a + b  _ ",a,"  + ",b," = ",soma)
   escrevaL("x = a - b  _ ",a,"  - ",b," = ",sub)
   escrevaL("x = a * b  _ ",a,"  * ",b," = ",mul)
   escrevaL("x = a / b  _ ",a,"  / ",b," = ",divi)

Fimalgoritmo
